spring:
  application:
    name: backend

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms?characterEncoding=UTF-8
    username: postgres
    password: popost

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8081
  servlet:
    context-path: /api

