server:
  port: 80
  servlet:
    context-path: /api

spring:
  profiles:
    default: prod

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rds-lms-dev.cta4egc6ioti.ap-northeast-2.rds.amazonaws.com:5432/lms?characterEncoding=UTF-8
    username: postgres
    password: popost

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true